.TH "GETHOSTIP" "1"
.SH "NAME"
gethostip \(em convert an IP address into various formats
.SH "SYNOPSIS"
.PP
\fBgethostip\fR [\fB-dxnf\fP]  [\fB\fIHOSTNAME|IP\fR\fP]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBgethostip\fR command.
.PP
The \fBgethostip\fR utility converts the given hostname or
IP address into a variety formats.  It is provided by the syslinux
package to make it easier to calculate the appropriate names for
pxelinux configuration files.  These filenames can be the complete
hexadecimal representation for a given IP address, or a partial
hexadecimal representation to match a range of IP addresses.

.SH "OPTIONS"
.PP
A summary of options is included below.
.IP "\fB-d\fP" 10
Output the IP address in decimal format.
.IP "\fB-x\fP" 10
Output the IP address in hexadecimal format.
.IP "\fB-n\fP" 10
Output the host's canonical name.
.IP "\fB-f\fP" 10
Full output.  Outputs the IP address in all supported formats.
Same as \fB-xdn\fP.

.SH "SEE ALSO"
.PP
\fBsyslinux\fR(1)

.PP
More details can be found in the pxelinux documentation, which
can be found in
\fB/usr/share/doc/syslinux/pxelinux.doc.gz\fP on
\fBDebian GNU/Linux\fP systems.

.SH "AUTHOR"
.PP
This manual page was compiled by dann frazier <dannf@debian.org> for
the \fBDebian GNU/Linux\fP system (but may be used by others).
