.TH isohybrid 1 "17 Jan 2014" "isohybrid"
.SH "NAME"
isohybrid \(em Post-process an ISO 9660 image for booting as a hard disk.
.SH "SYNOPSIS"
.B isohybrid
[\fBOPTIONS\fP]
.I <boot.iso>
.SH "DESCRIPTION"
.PP
The \fBisohybrid\fR utility modifies an ISO 9660 image generated with
mkisofs, genisoimage, or compatible utilities, to be bootable as a CD-ROM or
as a hard disk.
.SH "OPTIONS"
.TP
\fB-h\fR \fI<X>\fR\fN
.br
Number of geometry heads (default 64)
.TP
\fB-s\fR \fI<X>\fR
.br
Number of geometry sectors (default 32)
.TP
\fB-e\fR \fI<X>\fR, \fB--entry\fR \fI<X>\fR
Specify parititon entry number (1-4)
.TP
\fB-o\fR \fI<X>\fR, \fB--offset\fR \fI<X>\fR
.br
Specify partition offset (default 0)
.TP
\fB-t\fR \fI<X>\fR, \fB--type\fR \fI<X>\fR
.br
Specify partition type (default 0x17)
.TP
\fB-i\fR \fI<X>\fR, \fB--id\fR \fI<X>\fR
.br
Specify MBR ID (default random)
.TP
\fB-u\fR, \fB--uefi\fB
Build EFI bootable image
.TP
\fB-m\fR, \fB--mac\fB
Add Apple File Protocol partition table support
.TP
\fB--forcehd0\fR
Assume we are laoded as disk ID 0
.TP
\fB--ctrlhd0\fR
Assume disk ID 0 if the Ctrl key is pressed
.TP
\fB--partok\fR
Allow booting from within a partition
.TP
\fB-?\fR, \fB--help\fR
Display help
.TP
\fB-v\fR, \fB--verbose\fR
Display verbose output
.TP
\fB-V\fR, \fB--version\fR
Display version information

.SH "SEE ALSO"
.PP
\fBmkisofs\fR(1)
