.TH "LSS16TOPPM" "1"
.SH "NAME"
lss16toppm \(em Convert an LSS-16 image to PPM
.SH "SYNOPSIS"
.PP
\fBlss16toppm\fR [\fB-map\fP]  [< file.lss]  [> file.ppm]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBlss16toppm\fR       command.

.PP
The \fBlss16toppm\fR utility converts an LSS-16 image to a
PPM image.

.SH "OPTIONS"
.PP
A summary of options is included below.
.IP "\fB-map\fP" 10
Output the color map to standard error.
.SH "SEE ALSO"
.PP
\fBppmtolss16\fR(1)

.SH "AUTHOR"
.PP
This manual page was compiled by dann frazier <dannf@debian.org> for
the \fBDebian GNU/Linux\fP system (but may be used by others).
