.TH memdiskfind 1 "17 Jan 2014" "memdiskfind"
.SH "NAME"
memdiskfind \(em Simple utility to find a resident \fBmemdisk\fR instance.
.SH "SYNOPSIS"
.B memdiskfind
.SH "DESCRIPTION"
.PP
The \fBmemdiskfind\fR utility searches memory for a \fBmemdisk\fR instance,
and, if found, outputs the parameters needed to use the \fphram\fR driver in
Linux to map it.
