## -----------------------------------------------------------------------
##  $Id$
##
##   Copyright 1998-2001 H. Peter Anvin - All Rights Reserved
##
##   This program is free software; you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation, Inc., 675 Mass Ave, Cambridge MA 02139,
##   USA; either version 2 of the License, or (at your option) any later
##   version; incorporated herein by reference.
##
## -----------------------------------------------------------------------

#
# Main Makefile for SYSLINUX
#

CC	 = gcc
INCLUDE  =
CFLAGS	 = -Wall -O2 -fomit-frame-pointer
LDFLAGS	 = -O2 -s

NASM	 = nasm
NINCLUDE = 
BINDIR   = /usr/bin
LIBDIR   = /usr/lib/syslinux

PERL     = perl

VERSION  = $(shell cat version)

.c.o:
	$(CC) $(INCLUDE) $(CFLAGS) -c $<

#
# The BTARGET refers to objects that are derived from ldlinux.asm; we
# like to keep those uniform for debugging reasons; however, distributors 
# want to recompile the installers (ITARGET).
#
CSRC    = syslinux.c gethostip.c
NASMSRC  = ldlinux.asm syslinux.asm copybs.asm \
	  pxelinux.asm mbr.asm isolinux.asm
SOURCES = $(CSRC) $(NASMSRC) *.inc
BTARGET = ldlinux.bss ldlinux.sys ldlinux.bin ldlinux.lst \
	  pxelinux.0 mbr.bin isolinux.bin isolinux-debug.bin
ITARGET = syslinux.com syslinux copybs.com gethostip
DOCS    = COPYING NEWS README TODO *.doc sample
OTHER   = Makefile bin2c.pl now.pl genstupid.pl keytab-lilo.pl version \
	  sys2ansi.pl ppmtolss16 lss16toppm memdisk
OBSOLETE = pxelinux.bin

# Things to install in /usr/bin
INSTALL_BIN   =	syslinux gethostip ppmtolss16 lss16toppm
# Things to install in /usr/lib/syslinux
INSTALL_LIB   =	pxelinux.0 isolinux.bin isolinux-debug.bin \
		syslinux.com copybs.com memdisk/memdisk

# The DATE is set on the make command line when building binaries for
# official release.  Otherwise, substitute a hex string that is pretty much
# guaranteed to be unique to be unique from build to build.
ifndef HEXDATE
HEXDATE := $(shell $(PERL) now.pl ldlinux.asm pxelinux.asm isolinux.asm)
endif
ifndef DATE
DATE    := $(HEXDATE)
endif

all:	$(BTARGET) $(ITARGET) samples memdisk
	ls -l $(BTARGET) $(ITARGET) memdisk/memdisk

installer: $(ITARGET) samples
	ls -l $(BTARGET) $(ITARGET)

.PHONY: samples
samples:
	$(MAKE) -C sample all

.PHONY: memdisk
memdisk:
	$(MAKE) -C memdisk all

kwdhash.inc: keywords
	$(PERL) genhash.pl < keywords > kwdhash.inc

ldlinux.bin: ldlinux.asm kwdhash.inc
	$(NASM) -f bin -dVERSION="'$(VERSION)'" -dDATE_STR="'$(DATE)'" \
		-dHEXDATE="$(HEXDATE)" \
		-l ldlinux.lst -o ldlinux.bin ldlinux.asm
	$(PERL) genstupid.pl < ldlinux.lst

pxelinux.0: pxelinux.asm kwdhash.inc
	$(NASM) -f bin -dVERSION="'$(VERSION)'" -dDATE_STR="'$(DATE)'" \
		-dHEXDATE="$(HEXDATE)" \
		-l pxelinux.lst -o pxelinux.0 pxelinux.asm

isolinux.bin: isolinux.asm kwdhash.inc
	$(NASM) -f bin -dVERSION="'$(VERSION)'" -dDATE_STR="'$(DATE)'" \
		-dHEXDATE="$(HEXDATE)" \
		-l isolinux.lst -o isolinux.bin isolinux.asm

# Special verbose version of isolinux.bin
isolinux-debug.bin: isolinux.asm kwdhash.inc
	$(NASM) -f bin -dVERSION="'$(VERSION)'" -dDATE_STR="'$(DATE)'" \
		-dHEXDATE="$(HEXDATE)" -dDEBUG_MESSAGES \
		-l isolinux-debug.lst -o isolinux-debug.bin isolinux.asm

ldlinux.bss: ldlinux.bin
	dd if=ldlinux.bin of=ldlinux.bss bs=512 count=1

ldlinux.sys: ldlinux.bin
	dd if=ldlinux.bin of=ldlinux.sys  bs=512 skip=1

mbr.bin: mbr.asm
	$(NASM) -f bin -l mbr.lst -o mbr.bin mbr.asm

syslinux.com: syslinux.asm ldlinux.bss ldlinux.sys stupid.inc
	$(NASM) -f bin -l syslinux.lst -o syslinux.com syslinux.asm

copybs.com: copybs.asm
	$(NASM) -f bin -l copybs.lst -o copybs.com copybs.asm

bootsect_bin.c: ldlinux.bss bin2c.pl
	$(PERL) bin2c.pl bootsect < ldlinux.bss > bootsect_bin.c

ldlinux_bin.c: ldlinux.sys bin2c.pl
	$(PERL) bin2c.pl ldlinux < ldlinux.sys > ldlinux_bin.c

syslinux: syslinux.o bootsect_bin.o ldlinux_bin.o stupid.o
	$(CC) $(LDFLAGS) -o syslinux \
		syslinux.o bootsect_bin.o ldlinux_bin.o stupid.o

ldlinux.lst: ldlinux.bin
	: Generated by side effect

stupid.c: ldlinux.lst genstupid.pl
	$(PERL) genstupid.pl < ldlinux.lst

stupid.inc: stupid.c
	: Generated by side effect

stupid.o: stupid.c

gethostip.o: gethostip.c

gethostip: gethostip.o

install: installer
	mkdir -m 755 -p $(INSTALLROOT)$(BINDIR) $(INSTALLROOT)$(LIBDIR)
	install -m 755 -c $(INSTALL_BIN) $(INSTALLROOT)$(BINDIR)
	install -m 644 -c $(INSTALL_LIB) $(INSTALLROOT)$(LIBDIR)

local-tidy:
	rm -f *.o *_bin.c stupid.*
	rm -f syslinux.lst copybs.lst pxelinux.lst isolinux*.lst
	rm -f $(OBSOLETE)

tidy: local-tidy
	$(MAKE) -C memdisk tidy

local-clean:
	rm -f $(ITARGET)

clean: local-tidy local-clean
	$(MAKE) -C sample clean
	$(MAKE) -C memdisk clean

dist: tidy
	for dir in . sample memdisk ; do \
		( cd $$dir && rm -f *~ \#* core ) ; \
	done

local-spotless:
	rm -f $(BTARGET) .depend

spotless: local-clean dist local-spotless
	$(MAKE) -C sample spotless
	$(MAKE) -C memdisk spotless

.depend:
	rm -f .depend
	for csrc in $(CSRC) ; do $(CC) $(INCLUDE) -M $$csrc >> .depend ; done
	for nsrc in $(NASMSRC) ; do $(NASM) -DDEPEND $(NINCLUDE) -o `echo $$nsrc | sed -e 's/\.asm/\.bin/'` -M $$nsrc >> .depend ; done

depend:
	rm -f .depend
	$(MAKE) .depend

# Hook to add private Makefile targets for the maintainer.
-include Makefile.private

# Include dependencies file
-include .depend
